### ISSUE TITLE
[BUG] Server Status appearing Offline after updating to V1.56.1

### ISSUE THREAD

**Issue by scorpio862** [immich-app/immich#2477]
### The bug

After updating to V1.56.1 I the status of the server started showing Offline even if the WebUI still works fine and I can see the photos. 

The face recognition software didn't work properly and I was getting this errors in the log:

[Nest] 169  - 05/19/2023, 7:11:16 AM   ERROR [ExceptionsHandler] promises_1.default.statfs is not a function
TypeError: promises_1.default.statfs is not a function
    at FilesystemProvider.checkDiskUsage (/app/immich/server/dist/apps/immich/libs/infra/src/repositories/filesystem.provider.js:64:48)
    at ServerInfoService.getInfo (/app/immich/server/dist/apps/immich/libs/domain/src/server-info/server-info.service.js:28:55)
    at ServerInfoController.getServerInfo (/app/immich/server/dist/apps/immich/apps/immich/src/controllers/server-info.controller.js:24:29)
    at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (/app/immich/server/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
    at /app/immich/server/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/immich/server/node_modules/@nestjs/core/router/router-proxy.js:9:17

I went back to server version 1.56.0 and everyting works fine again and face recognition works again.
 

### The OS that Immich Server is running on

Unraid 6.12.0-rc6

### Version of Immich Server

V1.56.1

### Version of Immich Mobile App

V1.56.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Update server to V1.56.1
```

**Comment by bo0tzz** [comment]
What sort of filesystem is your library folder on?

**Comment by michelheusschen** [comment]
v1.56.1 changes the way of reading disk usage and requires NodeJS 18. Are you using the third-party [monolithic image](https://github.com/imagegenius/docker-immich) by chance? They still use NodeJS 16 which could cause these errors.

**Comment by scorpio862** [comment]
It looks like I am using "ghcr.io/imagegenius/immich" which was in Unraid template when installing Immich

**Comment by michelheusschen** [comment]
They have an [open PR](https://github.com/imagegenius/docker-immich/pull/81) that should fix this issue. You can keep using v1.56.0 in the meantime until their image is updated.

**Comment by hydazz** [comment]
this is fixed :)
