### ISSUE TITLE
[BUG] v1.67  immich-server fails to start due to missing node module

### ISSUE THREAD

**Issue by natedawg** [immich-app/immich#3248]
### The bug

After updating to v1.67 starting immich with the command docker-compose up throws the following error from the immich-server

```
immich-microservices_1     | Node.js v18.16.0
immich-server_1            | node:internal/modules/cjs/loader:1078
immich-server_1            |   throw err;
immich-server_1            |   ^
immich-server_1            | 
immich-server_1            | Error: Cannot find module '/usr/src/app/dist/main'
immich-server_1            |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
immich-server_1            |     at Module._load (node:internal/modules/cjs/loader:920:27)
immich-server_1            |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
immich-server_1            |     at node:internal/main/run_main_module:23:47 {
immich-server_1            |   code: 'MODULE_NOT_FOUND',
immich-server_1            |   requireStack: []
immich-server_1            | }

```

### The OS that Immich Server is running on

Docker on debian

### Version of Immich Server

v1.67

### Version of Immich Mobile App

v1.67

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    restart: unless-stopped
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data


  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    logging:
      driver: none
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always
volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Start the immich-server container and get an error that prevents running.
```

**Comment by danielboros** [comment]
Same. Reverting to `v1.66.1` fixes it so it appears to be related to `v1.67`.

**Comment by davewatson91** [comment]
Also experiencing this one. Docker Desktop (Windows).

**Comment by thespyboss** [comment]
> Same. Reverting to `v1.66.1` fixes it so it appears to be related to `v1.67`.

how did you revert to 1.66.1? it could be a workaround for the time being.

**Comment by thespyboss** [comment]
I'm also seeing this on Docker running on Debian 12.

**Comment by alextran1502** [comment]
It was fixed in 1.67.1 - sorry for the inconvenience
