### ISSUE TITLE
Immich doesn't compile with Python 3.13

### ISSUE THREAD

**Issue by Webbeh** [immich-app/immich#15038]
### The bug

I am trying to compile Immich (server) from source.

I run Arch with the latest software revision of everything, including Python - currently version 3.13.1 installed.

This version of python seems to prevent compilation of immich, see logs below.

Downgrading to 3.12 fixes the compilation error.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
- Not using docker
```

### Your .env content

```Shell
- Not related to the issue
```

### Reproduction steps

1. Get source from git
2. Compile

Compilation breaks when reaching the meson deprecation tests build.

Python 3.12 builds are working, python 3.13 breaks.

### Relevant log output

```
[108/1619] Compiling C object scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_def.c.o
  FAILED: scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_def.c.o
  cc -Iscipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p -Iscipy/_lib -I../scipy/_lib -I../scipy/_lib/src -I/usr/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 -Wno-unused-but-set-variable -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/home/build/.cache/yay/immich/src=/usr/src/debug/immich -flto=auto -fPIC -Wno-cpp -MD -MQ scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_def.c.o -MF scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_def.c.o.d -o scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_def.c.o -c scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c
  scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c:828:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
    828 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u) {
        | ^~~~~~
  scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c: In function ‘__Pyx_Py_UNICODE_strlen’:
  scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c:829:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
    829 |     const Py_UNICODE *u_end = u;
        |     ^~~~~
  scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c: In function ‘__Pyx_PyInt_As_long’:
  scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c:2486:27: error: too few arguments to function ‘_PyLong_AsByteArray’
   2486 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
        |                           ^~~~~~~~~~~~~~~~~~~
  In file included from /usr/include/python3.13/longobject.h:107,
                   from /usr/include/python3.13/Python.h:81,
                   from scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c:6:
  /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
    111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
        |                 ^~~~~~~~~~~~~~~~~~~
  scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c: In function ‘__Pyx_PyInt_As_int’:
  scipy/_lib/_test_deprecation_def.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_def.c:2682:27: error: too few arguments to function ‘_PyLong_AsByteArray’
   2682 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
        |                           ^~~~~~~~~~~~~~~~~~~
  /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
    111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
        |                 ^~~~~~~~~~~~~~~~~~~




  [109/1619] Compiling C object scipy/special/libcephes.a.p/cephes_stdtr.c.o
  [110/1619] Compiling C object scipy/special/libcephes.a.p/cephes_sinpi.c.o
  [111/1619] Compiling C object scipy/special/libcephes.a.p/cephes_unity.c.o
  [112/1619] Compiling C object scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_call.c.o
  FAILED: scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_call.c.o
  cc -Iscipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p -Iscipy/_lib -I../scipy/_lib -I../scipy/_lib/src -I/usr/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 -Wno-unused-but-set-variable -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/home/build/.cache/yay/immich/src=/usr/src/debug/immich -flto=auto -fPIC -Wno-cpp -MD -MQ scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_call.c.o -MF scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_call.c.o.d -o scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/meson-generated__test_deprecation_call.c.o -c scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c
  scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c:828:1: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
    828 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u) {
        | ^~~~~~
  scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c: In function ‘__Pyx_Py_UNICODE_strlen’:
  scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c:829:5: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
    829 |     const Py_UNICODE *u_end = u;
        |     ^~~~~
  scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c: In function ‘__Pyx_PyInt_As_long’:
  scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c:2248:27: error: too few arguments to function ‘_PyLong_AsByteArray’
   2248 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
        |                           ^~~~~~~~~~~~~~~~~~~
  In file included from /usr/include/python3.13/longobject.h:107,
                   from /usr/include/python3.13/Python.h:81,
                   from scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c:6:
  /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
    111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
        |                 ^~~~~~~~~~~~~~~~~~~
  scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c: In function ‘__Pyx_PyInt_As_int’:
  scipy/_lib/_test_deprecation_call.cpython-313-x86_64-linux-gnu.so.p/_test_deprecation_call.c:2444:27: error: too few arguments to function ‘_PyLong_AsByteArray’
   2444 |                 int ret = _PyLong_AsByteArray((PyLongObject *)v,
        |                           ^~~~~~~~~~~~~~~~~~~
  /usr/include/python3.13/cpython/longobject.h:111:17: note: declared here
    111 | PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
        |                 ^~~~~~~~~~~~~~~~~~~
```

### Additional information

Immich-server 1.121.0 is currently running fine on that machine.

EDIT: I have tried updating the dependencies for `immich-machine-learning` to their latest version. Everything seemed to compile alright with the exception of `onnx`, which seems broken in 3.13.
According to https://github.com/onnx/onnx/issues/6339, the latest onnx-weekly supports python 3.13.

**Comment by danieldietzler** [comment]
I don't see why this is an issue. Nothing is broken and it's not unusual that software only supports specific versions.
