### ISSUE TITLE
JPEG failed thumbnail generation and wrong aspect ratio

### ISSUE THREAD

**Issue by cachapa** [immich-app/immich#30492]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I'm getting failed thumbnail generation when importing old pictures. Opening the picture works but with bad aspect ratio:

Album view:
<img width="256" height="282" alt="Image" src="https://github.com/user-attachments/assets/c1151870-a7a8-430e-97d9-3590644956d4" />

Opening the picture (notice the bad aspect ratio and lack of EXIF):
<img width="910" height="968" alt="Image" src="https://github.com/user-attachments/assets/6adbbd4b-841c-4c39-ac1b-a8987f56b198" />

For comparison, the same picture in the Gnome image viewer:
<img width="925" height="1025" alt="Image" src="https://github.com/user-attachments/assets/b822197e-6131-4b4f-9857-62a867c781b3" />

`magick original.jpg copy.jpg` doesn't report any errors and importing the copy has the same issues.

The Immich logs indicate the error might be linked to the lens EXIF info:

```
[Nest] 7  - 08/02/2026, 8:34:03 AM   ERROR [Microservices:{"id":"f907818d-5118-4d96-9499-127f6ada073d","source":"upload"}] Unable to run job handler (AssetExtractMetadata): TypeError: (exifTags.LensID ?? exifTags.LensType ?? exifTags.LensSpec ?? exifTags.LensModel ?? "").trim is not a function
TypeError: (exifTags.LensID ?? exifTags.LensType ?? exifTags.LensSpec ?? exifTags.LensModel ?? "").trim is not a function
    at getLensModel (/usr/src/app/server/dist/services/metadata.service.js:92:111)
    at MetadataService.handleMetadataExtraction (/usr/src/app/server/dist/services/metadata.service.js:219:24)
    at async JobService.onJobRun (/usr/src/app/server/dist/services/job.service.js:78:30)
    at async EventRepository.onEvent (/usr/src/app/server/dist/repositories/event.repository.js:91:13)
    at async /usr/src/app/server/node_modules/.pnpm/bullmq@5.80.5/node_modules/bullmq/dist/cjs/classes/worker.js:589:32
```

The bad picture's EXIF info:
```
$ exiv2 bad.jpg 
File name       : bad.jpg
File size       : 110022 Bytes
MIME type       : image/jpeg
Image size      : 1067 x 1600
Thumbnail       : None
Camera make     : Canon
Camera model    : Canon EOS 400D DIGITAL
Image timestamp : 2007:02:05 01:56:55
File number     : 
Exposure time   : 1/90 s
Aperture        : F1.8
Exposure bias   : +2 EV
Flash           : No, compulsory
Flash bias      : 0 EV
Focal length    : 50.0 mm
Subject distance: 0 m
ISO speed       : 800
Exposure mode   : Aperture priority
Metering mode   : Partial
Macro mode      : (0)
Image quality   : unkown
White balance   : (38656)
Copyright       : 
Exif comment    : charset=Ascii 
```

<img width="1067" height="1600" alt="Image" src="https://github.com/user-attachments/assets/328b73d8-94f4-48aa-a4b2-7b8aa31a61ce" />

For comparison, a picture from the same batch that imported correctly:
```
$ exiv2 good.jpg 
File name       : good.jpg
File size       : 240861 Bytes
MIME type       : image/jpeg
Image size      : 1067 x 1600
Thumbnail       : image/jpeg, 4637 Bytes
Camera make     : Canon
Camera model    : Canon EOS 400D DIGITAL
Image timestamp : 2007:02:04 16:59:23
File number     : 
Exposure time   : 1/90 s
Aperture        : F2.5
Exposure bias   : 0 EV
Flash           : No, compulsory
Flash bias      : (64512)
Focal length    : 50.0 mm
Subject distance: 0 m
ISO speed       : 400
Exposure mode   : Aperture priority
Metering mode   : Partial
Macro mode      : (0)
Image quality   : unkown
White balance   : (256)
Copyright       : 
Exif comment    : charset=Ascii 
```

<img width="1067" height="1600" alt="Image" src="https://github.com/user-attachments/assets/61d14999-3417-4e24-b0b8-6fec40c6486b" />

### The OS that Immich Server is running on

Debian 12 (Raspberrry Pi 5 8GB)

### Version of Immich Server

v3.1.0

### Version of Immich Mobile App

3.1.0.build.3057

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://docs.immich.app/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v2.1.0"
IMMICH_VERSION=v3

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=**************

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=********
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload attached image
2. Wait for thumbnail generation
3. Thumbnail fails to generate, opening image shows bad aspect ratio

<img width="1067" height="1600" alt="Image" src="https://github.com/user-attachments/assets/328b73d8-94f4-48aa-a4b2-7b8aa31a61ce" />

### Relevant log output

```shell
[Nest] 7  - 08/02/2026, 8:34:03 AM   ERROR [Microservices:{"id":"f907818d-5118-4d96-9499-127f6ada073d","source":"upload"}] Unable to run job handler (AssetExtractMetadata): TypeError: (exifTags.LensID ?? exifTags.LensType ?? exifTags.LensSpec ?? exifTags.LensModel ?? "").trim is not a function
TypeError: (exifTags.LensID ?? exifTags.LensType ?? exifTags.LensSpec ?? exifTags.LensModel ?? "").trim is not a function
    at getLensModel (/usr/src/app/server/dist/services/metadata.service.js:92:111)
    at MetadataService.handleMetadataExtraction (/usr/src/app/server/dist/services/metadata.service.js:219:24)
    at async JobService.onJobRun (/usr/src/app/server/dist/services/job.service.js:78:30)
    at async EventRepository.onEvent (/usr/src/app/server/dist/repositories/event.repository.js:91:13)
    at async /usr/src/app/server/node_modules/.pnpm/bullmq@5.80.5/node_modules/bullmq/dist/cjs/classes/worker.js:589:32
```

**Comment by bo0tzz** [comment]
@danieldietzler this seems like a regression from https://github.com/immich-app/immich/pull/29684/changes#diff-61222a9e424956861d68b088bbb08a464f1fa5d8a8c8fa7a3cfa116ae1f8170fR120 (metadata.service.ts line 120, and I think there's other similar cases there too)

**Comment by danieldietzler** [comment]
Hey @cachapa, could you please send the output of `exiftool -json` instead of `exiv2`? I am curious how any of these could not be a string

**Comment by cachapa** [comment]
@danieldietzler sure, I'm sending both the bad and good jpegs for comparison:

bad.jpg
``` json
[{
  "SourceFile": "bad.jpg",
  "ExifToolVersion": 13.50,
  "FileName": "bad.jpg",
  "Directory": ".",
  "FileSize": "110 kB",
  "FileModifyDate": "2010:05:01 22:17:30+02:00",
  "FileAccessDate": "2026:08:02 11:05:48+02:00",
  "FileInodeChangeDate": "2026:08:02 11:05:44+02:00",
  "FilePermissions": "-rwx-----x",
  "FileType": "JPEG",
  "FileTypeExtension": "jpg",
  "MIMEType": "image/jpeg",
  "JFIFVersion": 1.01,
  "ExifByteOrder": "Little-endian (Intel, II)",
  "Make": "Canon",
  "Model": "Canon EOS 400D DIGITAL",
  "Orientation": "Unknown (0)",
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": "inches",
  "Software": "f-spot version 0.6.1.5",
  "ModifyDate": "2010:05:01 22:17:30",
  "YCbCrPositioning": "Co-sited",
  "ExposureTime": "1/90",
  "FNumber": 1.8,
  "ExposureProgram": "Aperture-priority AE",
  "ISO": 800,
  "ExifVersion": "0221",
  "DateTimeOriginal": "2007:02:05 01:56:55",
  "CreateDate": "2007:02:05 01:56:55",
  "ComponentsConfiguration": "Y, Cb, Cr, -",
  "ShutterSpeedValue": "1/90",
  "ApertureValue": 1.8,
  "ExposureCompensation": "+2",
  "MeteringMode": "Partial",
  "Flash": "Off, Did not fire",
  "FocalLength": "50.0 mm",
  "Warning": "[minor] Invalid CanonCameraSettings data",
  "FocalPlaneYSize": "442.16 mm",
  "CanonImageType": " 400D DIGITAL",
  "CanonFirmwareVersion": "1.0.4",
  "OwnerName": "chapa",
  "SerialNumber": "0630303783",
  "CanonModelID": "EOS Digital Rebel XTi / 400D / Kiss Digital X",
  "ThumbnailImageValidArea": "30208 37008 0 0",
  "SerialNumberFormat": "Format 2",
  "OriginalDecisionDataOffset": 0,
  "LensModel": 1.8,
  "InternalSerialNumber": "",
  "DustRemovalData": "(Binary data 1024 bytes, use -b option to extract)",
  "CropLeftMargin": 0,
  "CropRightMargin": 768,
  "CropTopMargin": 0,
  "CropBottomMargin": 0,
  "VRDOffset": 0,
  "ColorDataVersion": "Unknown (13057)",
  "WB_RGGBLevelsAsShot": "-32493 11 4 4",
  "ColorTempAsShot": -8185,
  "WB_RGGBLevelsAuto": "-21485 -499 3 -8188",
  "ColorTempAuto": -8185,
  "WB_RGGBLevelsMeasured": "13331 9 4 -15612",
  "ColorTempMeasured": 20485,
  "WB_RGGBLevelsDaylight": "-8940 10 4 -15100",
  "ColorTempDaylight": 22532,
  "WB_RGGBLevelsShade": "2587 10 4 14340",
  "ColorTempShade": 28677,
  "WB_RGGBLevelsCloudy": "28439 14854 14852 -21756",
  "ColorTempCloudy": -32759,
  "WB_RGGBLevelsTungsten": "-16116 4359 4356 16388",
  "ColorTempTungsten": -18168,
  "WB_RGGBLevelsFluorescent": "13326 9 4 -15612",
  "ColorTempFluorescent": 23045,
  "WB_RGGBLevelsKelvin": "17428 10 4 6660",
  "ColorTempKelvin": 32005,
  "WB_RGGBLevelsFlash": "24 2 4 -252",
  "ColorTempFlash": -23009,
  "WB_RGGBLevelsPC1": "15 2 4 -252",
  "ColorTempPC1": -23009,
  "WB_RGGBLevelsPC2": "15 2 4 -252",
  "ColorTempPC2": -23009,
  "WB_RGGBLevelsPC3": "-10481 23044 23044 -26876",
  "ColorTempPC3": -12276,
  "WB_RGGBLevelsCustom": "23049 17662 513 -27644",
  "ColorTempCustom": 27690,
  "PerChannelBlackLevel": "0 0 0 0",
  "FlashOutput": "Strobe or Misfire",
  "FlashBatteryLevel": "0.11V",
  "MeasuredRGGBData": "2164262180 1207959750 263428 4",
  "PictureStyleUserDef": "None; None; None",
  "PictureStylePC": "None; None; None",
  "CustomPictureStyleFileName": "",
  "UserComment": "",
  "FlashpixVersion": "0100",
  "ColorSpace": "Uncalibrated",
  "ExifImageWidth": 1067,
  "ExifImageHeight": 1600,
  "InteropIndex": "R98 - DCF basic file (sRGB)",
  "InteropVersion": "0100",
  "FocalPlaneXResolution": 4433.295325,
  "FocalPlaneYResolution": 4453.608247,
  "FocalPlaneResolutionUnit": "inches",
  "CustomRendered": "Normal",
  "ExposureMode": "Auto",
  "WhiteBalance": "Auto",
  "SceneCaptureType": "Standard",
  "CurrentIPTCDigest": "0cc2bded349bddded77246167d550ccf",
  "By-line": "Picasa 2.6",
  "ImageWidth": 1067,
  "ImageHeight": 1600,
  "EncodingProcess": "Baseline DCT, Huffman coding",
  "BitsPerSample": 8,
  "ColorComponents": 3,
  "YCbCrSubSampling": "YCbCr4:2:0 (2 2)",
  "Aperture": 1.8,
  "ImageSize": "1067x1600",
  "Megapixels": 1.7,
  "ShutterSpeed": "1/90",
  "LightValue": 5.2,
  "ScaleFactor35efl": 1.6,
  "CircleOfConfusion": "0.019 mm",
  "FOV": "25.1 deg",
  "FocalLength35efl": "50.0 mm (35 mm equivalent: 80.9 mm)",
  "HyperfocalDistance": "74.81 m"
}]
```

good.jpg
``` json
[{
  "SourceFile": "good.jpg",
  "ExifToolVersion": 13.50,
  "FileName": "good.jpg",
  "Directory": ".",
  "FileSize": "241 kB",
  "FileModifyDate": "2010:05:01 22:17:39+02:00",
  "FileAccessDate": "2026:08:02 11:06:24+02:00",
  "FileInodeChangeDate": "2026:08:02 11:05:41+02:00",
  "FilePermissions": "-rwx-----x",
  "FileType": "JPEG",
  "FileTypeExtension": "jpg",
  "MIMEType": "image/jpeg",
  "JFIFVersion": 1.01,
  "ExifByteOrder": "Little-endian (Intel, II)",
  "Make": "Canon",
  "Model": "Canon EOS 400D DIGITAL",
  "XResolution": 72,
  "YResolution": 72,
  "ResolutionUnit": "inches",
  "Software": "f-spot version 0.6.1.5",
  "ModifyDate": "2010:05:01 22:17:39",
  "YCbCrPositioning": "Co-sited",
  "ExposureTime": "1/90",
  "FNumber": 2.5,
  "ExposureProgram": "Aperture-priority AE",
  "ISO": 400,
  "ExifVersion": "0221",
  "DateTimeOriginal": "2007:02:04 16:59:23",
  "CreateDate": "2007:02:04 16:59:23",
  "ComponentsConfiguration": "Y, Cb, Cr, -",
  "ShutterSpeedValue": 0,
  "ApertureValue": 2.5,
  "ExposureCompensation": 0,
  "MeteringMode": "Partial",
  "Flash": "Off, Did not fire",
  "FocalLength": "50.0 mm",
  "Warning": "[minor] Invalid CanonCameraSettings data",
  "FocalType": "Unknown (18432)",
  "FocalPlaneXSize": "1352.50 mm",
  "CanonImageType": "L",
  "CanonFirmwareVersion": "",
  "OwnerName": "",
  "SerialNumber": "0630303783",
  "CanonModelID": "EOS Digital Rebel XTi / 400D / Kiss Digital X",
  "ThumbnailImageValidArea": "65535 255 0 0",
  "SerialNumberFormat": "Format 2",
  "OriginalDecisionDataOffset": 0,
  "LensModel": "",
  "InternalSerialNumber": "",
  "DustRemovalData": "(Binary data 1024 bytes, use -b option to extract)",
  "CropLeftMargin": 0,
  "CropRightMargin": 0,
  "CropTopMargin": 20608,
  "CropBottomMargin": 33044,
  "VRDOffset": 0,
  "ColorDataVersion": "Unknown (4)",
  "WB_RGGBLevelsAsShot": "-758 515 -31996 16900",
  "ColorTempAsShot": 13341,
  "WB_RGGBLevelsAuto": "9 4 -15612 20485",
  "ColorTempAuto": -8940,
  "WB_RGGBLevelsMeasured": "10 4 -15100 22532",
  "ColorTempMeasured": 2587,
  "WB_RGGBLevelsDaylight": "10 4 14340 28677",
  "ColorTempDaylight": 28439,
  "WB_RGGBLevelsShade": "14854 14852 -21756 -32759",
  "ColorTempShade": -16116,
  "WB_RGGBLevelsCloudy": "4359 4356 16388 -18168",
  "ColorTempCloudy": 13326,
  "WB_RGGBLevelsTungsten": "9 4 -15612 23045",
  "ColorTempTungsten": 17428,
  "WB_RGGBLevelsFluorescent": "10 4 6660 32005",
  "ColorTempFluorescent": 24,
  "WB_RGGBLevelsKelvin": "2 4 -252 -23009",
  "ColorTempKelvin": 15,
  "WB_RGGBLevelsFlash": "2 4 -252 -23009",
  "ColorTempFlash": 15,
  "WB_RGGBLevelsPC1": "2 4 -252 -23009",
  "ColorTempPC1": -10481,
  "WB_RGGBLevelsPC2": "23044 23044 -26876 -12276",
  "ColorTempPC2": 23049,
  "WB_RGGBLevelsPC3": "17662 513 -27644 27690",
  "ColorTempPC3": 19710,
  "WB_RGGBLevelsCustom": "-6655 4099 -25049 25086",
  "ColorTempCustom": -24063,
  "PerChannelBlackLevel": "9472 8704 8704 10496",
  "FlashOutput": "Strobe or Misfire",
  "FlashBatteryLevel": "-543.66V",
  "MeasuredRGGBData": "4 0 0 4278190111",
  "PictureStyleUserDef": "None; None; None",
  "PictureStylePC": "None; None; None",
  "CustomPictureStyleFileName": "",
  "UserComment": "",
  "FlashpixVersion": "0100",
  "ColorSpace": "Uncalibrated",
  "ExifImageWidth": 1067,
  "ExifImageHeight": 1600,
  "FocalPlaneXResolution": 4453.608247,
  "FocalPlaneYResolution": 4433.295325,
  "FocalPlaneResolutionUnit": "inches",
  "ImageUniqueID": "fa417ebe64dfaec4ea368c19321180ab",
  "Compression": "JPEG (old-style)",
  "ThumbnailOffset": 5644,
  "ThumbnailLength": 4637,
  "CurrentIPTCDigest": "0cc2bded349bddded77246167d550ccf",
  "By-line": "Picasa 2.6",
  "ImageWidth": 1067,
  "ImageHeight": 1600,
  "EncodingProcess": "Baseline DCT, Huffman coding",
  "BitsPerSample": 8,
  "ColorComponents": 3,
  "YCbCrSubSampling": "YCbCr4:2:0 (2 2)",
  "Aperture": 2.5,
  "ImageSize": "1067x1600",
  "Megapixels": 1.7,
  "ShutterSpeed": "1/90",
  "ThumbnailImage": "(Binary data 4637 bytes, use -b option to extract)",
  "LightValue": 7.1,
  "ScaleFactor35efl": 1.6,
  "CircleOfConfusion": "0.019 mm",
  "FOV": "25.1 deg",
  "FocalLength35efl": "50.0 mm (35 mm equivalent: 80.9 mm)",
  "HyperfocalDistance": "53.86 m"
}]
```

**Comment by cachapa** [comment]
Looks like it's LensModel: it's a float in bad.jpg and an empty string on good.jpg.

**Comment by danieldietzler** [comment]
Wtf is `LensModel: 1.8` lol

**Comment by cachapa** [comment]
It's a Canon 50mm 1.8 so I'm guessing it's supposed to be the aperture?

I was using Picasa at the time to manage my library so it might have come from there, just weird that it only happened on some pictures.

**Comment by danieldietzler** [comment]
Makes sense. I did open #30512 but if you can guarantee me that this was an issue with picasa and the camera doesn't actually put the aperture there, I'd prefer not to merge the PR

**Comment by cachapa** [comment]
Unfortunately I cannot guarantee it since I no longer have that camera or lens so I cannot test.

**Comment by danieldietzler** [comment]
Fair enough then. I suppose the PR doesn't hurt per se, and it's always good to be defensive when it comes to exif parsing lol

**Comment by cachapa** [comment]
I understand your reluctance, especially since it cascades downstream to clients not being able to know what type that particular field is.

Perhaps the best solution would be to convert it to string on ingestion to at least guarantee clients should expect it to be a string as defined by the standard (not sure this is what your PR does already).

**Comment by danieldietzler** [comment]
That's essentially what this PR does. And as bo0tzz pointed out we did have that `String()` parsing there before, so it's fineeee

**Comment by danieldietzler** [comment]
You will have to re-run metadata extraction in the next release then, as well as missing thumbnail gen to fix the assets then

**Comment by cachapa** [comment]
That's fine, I marked all my albums with broken pictures so I can verify them when the update drops. Thanks!

**Comment by LargoUsagi** [comment]
I ran into this from another source and took the merged patch and hot fixed the container I am running and it resolved the issue, in my case the values were integers and not floats, may be worth noting on the test case.
