### ISSUE TITLE
WebUI not showing photos after May 30th after 1.135.0 update

### ISSUE THREAD

**Issue by clayauld** [immich-app/immich#19265]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After I updated my server to v1.135.0 the WebUI is only showing pictures up to May 30, 2025. I know there are more photos since then, and the app show they are uploaded (cloud with checkmark). They don't show up on any accounts on the WebUI. 

### The OS that Immich Server is running on

UnRAID OS

### Version of Immich Server

v1.35.0

### Version of Immich Mobile App

1.135.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
#      - ${APPDATA_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video_cache
      - /etc/localtime:/etc/localtime:ro
    environment:
      IMMICH_WORKERS_INCLUDE: 'api'
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
  #    - ${APPDATA_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video_cache
      - /etc/localtime:/etc/localtime:ro
    environment:
      IMMICH_WORKERS_EXCLUDE: 'api'
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
#     extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
#       file: hwaccel.ml.yml
#       service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${APPDATA_LOCATION}/model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${APPDATA_LOCATION}/pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
  
  # power-tools:
  #   container_name: immich_power_tools
  #   image: ghcr.io/varun-raj/immich-power-tools:latest
  #   ports:
  #     - "8001:3000"
  #   env_file:
  #     - .env

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# Debug level
#LOG_LEVEL=debug

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/Photos/immich
APPDATA_LOCATION=/mnt/user/appdata/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.135.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

# Immich Power Tools
IMMICH_API_KEY = <redacted>
IMMICH_URL = http://immich_server:2283 # Your immich instance ip address and port
EXTERNAL_IMMICH_URL = "<redacted>" # External address of immich

# Optional
GOOGLE_MAPS_API_KEY= <redacted> # Google Maps API Key
GEMINI_API_KEY= <redacted> # Gemini API Key

#For DB Using Individual Keys
#DB_USERNAME=${DB_USERNAME} # Postgress Database Username
#DB_PASSWORD = ${DB_PASSWORD} # Postgres Database Password
DB_HOST = immich_postgres # Postgres Host (IP address or hostname of the database)
DB_PORT = "5432" # Postgres Port number (Default: 5432)
#DB_DATABASE_NAME = "" # Name of the database 
#For DB using DB URL
#DB_URL = ""
```

### Reproduction steps

1. Update Immich server to v1.135.0 from v1.134.0
2. Open WebUI and check status
3. All accounts in WebUI do not show any pictures after May 30, 2025
...

### Relevant log output

```shell

```

### Additional information

I cleared the browser cache as well as the app cache and logged in again to both to make sure the photos were uploaded. The app is showing the photos are uploaded to the server.

**Comment by bo0tzz** [comment]
Are they just missing from the timeline or is there a blank section? Are there any errors in the browser console or server logs?

**Comment by tbelway** [comment]
Same problem. No errors in the log, and the albums I made in June show they have photos for the photo count but nothing visible.

The issue seems to be isolated to web version as they show up on the app (android). And if i try to re-upload the photos it correctly identifies them as duplicates.

**Comment by hellcry37** [comment]
same

**Comment by alextran1502** [comment]
Can you help open the developer console (F12) and see if there are any error messages?

**Comment by hellcry37** [comment]
```txt
The resource at “https://pictures.domain.ro/_app/immutable/assets/Overpass.DCP28BvT.ttf” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. photos
The resource at “https://pictures.domain.ro/_app/immutable/assets/OverpassMono.XkUhFDDw.ttf” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. photos
Empty string passed to getElementById(). 12 ac0e3b68-6e65-4bed-9195-e46857fe4d21
Uncaught (in promise) TypeError: this.assetsIterator().find is not a function
    Immutable 17
    async* https://pictures.domain.ro/photos:188
    promise callback* https://pictures.domain.ro/photos:187
DJ95cIEk.js:1:12315
    pt Immutable
    AsyncFunctionThrow self-hosted:811
    Immutable 10
    InterpretGeneratorResume self-hosted:1420
    AsyncFunctionNext self-hosted:807
    (Async: async)
    Rn Immutable
    InterpretGeneratorResume self-hosted:1420
    AsyncFunctionNext self-hosted:807
    (Async: async)
    <anonymous> https://pictures.domain.ro/photos:188
    (Async: promise callback)
    <anonymous> https://pictures.domain.ro/photos:187
Uncaught (in promise) TypeError: this.assetsIterator().find is not a function
    Immutable 23
    async* https://pictures.domain.ro/photos:188
    promise callback* https://pictures.domain.ro/photos:187
```
This is what I got when I try to press to go next picture on web. Used to work ok on v1.135.0, the rest from what I saw only non errors like ststus 200 etc

**Comment by alextran1502** [comment]
@hellcry37 Ah you are using an old browser version that isn't support the API. Which browser version are you using?

**Comment by hellcry37** [comment]
> [@hellcry37](https://github.com/hellcry37) Ah you are using an old browser version that isn't support the API. Which browser version are you using?

Seem indeed you are right, at least for me (I am using Mercury 129.0.2 that worked perfectly until this version), tested on Firefox latest version there is no issue at first glance, also tested with LibreWolf 139.0.4-1 and seem to work ok.

So something changed that this browser I use is not supported proper? Maybe the same issue as other guys?

**Comment by desoo40** [comment]
Same problem on Mac. Windows PC is OK

Mac Safari Version 18.0 (20619.1.26.31.6) console log
`Unhandled Promise Rejection: TypeError: this.assetsIterator().find is not a function. (In 'this.assetsIterator().find(e=>e.id===t.id)', 'this.assetsIterator().find' is undefined)`

Repro steps:
1. Open timeline and scroll down (not always reproduced)
2. Open some photo and click on arrow back to timeline

Screens
![Image](https://github.com/user-attachments/assets/e4c692c2-e877-47ad-b521-73d23a7bf89c)

Mac Chrome Version 108.0.5359.124 (Official Build) (arm64)
`Uncaught (in promise) TypeError: this.assetsIterator(...).find is not a function
    at U.findAssetById (DJ95cIEk.js:1:12315)
    at v (DJ95cIEk.js:1:12806)
    at S.findMonthGroupForAsset (DJ95cIEk.js:1:22314)
    at Fe (DLf0_xvm.js:2:17796)
    at ze (DLf0_xvm.js:2:18029)`

Also looks like

![Image](https://github.com/user-attachments/assets/3a332a85-b664-45f3-b627-5ead57f27888)

Make a note about UI side menu effects. Selected or highlighted elements are not readable

**Comment by alextran1502** [comment]
So those browsers are old, and do not support the API we just put in. Will look into a fix

**Comment by desoo40** [comment]
> So those browsers are old, and do not support the API we just put in. Will look into a fix

OK i'll update them. Thanks

**Comment by clayauld** [comment]
This issue is still present in 1.135.1. I am able to create an album with all the new photos since June 30, and it shows assets. However nothing shows up in the web UI.

This is isolated to the web interface. I can reproduce the problems in Chrome, Firefox, Brave browsers (so far tested on Android web browsers).
